### ISSUE TITLE
Privacy concern? - Export data from statistics

### ISSUE THREAD

**Issue by ghost** [young-europe/Members-Platform-bug-reports#144]
Lars Van Bourgognie
2021/11/02

Even though functional, and unsure whether this is an IO admin function or a future NC Manager function, the export data function exports data from all participants without time limits. It gives the e-mail addresses of all participants.

**Not sure if this complies with GDPR regulations**.

**Comment by valboyko** [comment]
Hi Lars,

Thanks for sharing the concern! The feature is complicit with the Privacy Policy and T&C we have in place. The export of all data is only available to IO and Admin roles. NC managers will be able to export data for users that are associated with their NCs and their events. NC managers can export the event participant lists. Otherwise, no other users could export any lists.

During each export, the user is prompted with a message asking them to handle the data carefully and in accordance with the GDPR standards.

Best,
Val
